### ISSUE TITLE
Missing basque definitions

### ISSUE THREAD

**Issue by gdomingu** [kantord/LibreLingo#1615]
**Describe the bug**
`yarn exportCourse basque-from-english` fails due to missing definitions.

**To Reproduce**
1. run `yarn exportCourse basque-from-english`

**Expected behavior**
`✅ Exported course basque-from-english`

**Screenshots**
```
⏳ Exporting course basque-from-englishTraceback (most recent call last):
  File "/workspaces/LibreLingo/apps/librelingo_json_export/librelingo_json_export/export.py", line 30, in _export_skill
    skill_data = _get_skill_data(skill, course)
  File "/workspaces/LibreLingo/apps/librelingo_json_export/librelingo_json_export/skills.py", line 13, in _get_skill_data
    "challenges": _get_challenges_data(skill, course),
  File "/workspaces/LibreLingo/apps/librelingo_json_export/librelingo_json_export/challenges.py", line 63, in _get_challenges_data
    _make_challenges_using(_get_word_challenges, skill.words, course),
  File "/workspaces/LibreLingo/apps/librelingo_json_export/librelingo_json_export/challenges.py", line 13, in _make_challenges_using
    for challenge in callback(data_item, course):
  File "/workspaces/LibreLingo/apps/librelingo_json_export/librelingo_json_export/challenges.py", line 51, in _get_word_challenges
    return _challenge_mapper(
  File "/workspaces/LibreLingo/apps/librelingo_json_export/librelingo_json_export/challenges.py", line 29, in map_challenge_creators
    for challenge in challenge_type_callback(item, course):
  File "/workspaces/LibreLingo/apps/librelingo_json_export/librelingo_json_export/challenge_types.py", line 48, in get_short_input_challenge
    "phrase": _define_words_in_sentence(
  File "/workspaces/LibreLingo/apps/librelingo_json_export/librelingo_json_export/dictionary.py", line 65, in _define_words_in_sentence
    return [_define_word(course, word, reverse) for word in words]
  File "/workspaces/LibreLingo/apps/librelingo_json_export/librelingo_json_export/dictionary.py", line 65, in <listcomp>
    return [_define_word(course, word, reverse) for word in words]
  File "/workspaces/LibreLingo/apps/librelingo_json_export/librelingo_json_export/dictionary.py", line 52, in _define_word
    raise ValueError(
ValueError: The English word "all" does not have a definition. Please add it to the mini-dictionary.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "librelingo_json_export/cli.py", line 42, in <module>
    _command()
  File "/home/codespace/.cache/pypoetry/virtualenvs/librelingo-json-export-oTdPRWce-py3.8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/codespace/.cache/pypoetry/virtualenvs/librelingo-json-export-oTdPRWce-py3.8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/codespace/.cache/pypoetry/virtualenvs/librelingo-json-export-oTdPRWce-py3.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/codespace/.cache/pypoetry/virtualenvs/librelingo-json-export-oTdPRWce-py3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "librelingo_json_export/cli.py", line 38, in _command
    export_course(output_path, course, settings)
  File "/workspaces/LibreLingo/apps/librelingo_json_export/librelingo_json_export/export.py", line 93, in export_course
    _export_course_skills(export_path, course, settings)
  File "/workspaces/LibreLingo/apps/librelingo_json_export/librelingo_json_export/export.py", line 19, in _export_course_skills
    _export_skill(export_path, skill, course, settings)
  File "/workspaces/LibreLingo/apps/librelingo_json_export/librelingo_json_export/export.py", line 32, in _export_skill
    raise RuntimeError(
RuntimeError: Error while exporting skill "Basics-3": The English word "all" does not have a definition. Please add it to the mini-dictionary.
⚠️  Couldn't export course basque-from-english
```

**Additional context**

**Comment by kantord** [comment]
cc. @RGBradley , not sure if you are aware of this

**Comment by prahasR** [comment]
Hi @gdomingu , is the issue still open, can you elaborate a more over what might be the reason for the error?

**Comment by RGBradley** [comment]
I corrected this in my repository but new file hasn't been pulled into main

**Comment by RGBradley** [comment]
this should be closed now

**Comment by kantord** [comment]
thanks @RGBradley
