### ISSUE TITLE
Export a course fails: missing slugify

### ISSUE THREAD

**Issue by szabgab** [kantord/LibreLingo#1799]
After following the instructions on https://librelingo.app/docs/ to set up a local environment I tried to export the sole course that can be found in `apps/web/src/courses/`. This is the error I get:

```
 ./scripts/exportYamlCourse.sh test
⏳ Exporting course testTraceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/app/apps/librelingo_json_export/librelingo_json_export/__init__.py", line 5, in <module>
    import librelingo_json_export.export
  File "/app/apps/librelingo_json_export/librelingo_json_export/export.py", line 4, in <module>
    from slugify import slugify
ModuleNotFoundError: No module named 'slugify'
⚠️  Couldn't export course test
```

```
$ poetry --version
Poetry version 1.1.11
$ poetry run python --version
Python 3.9.2
```

**Comment by szabgab** [comment]
OK, I found the issue. The following had to be executed:

```
cd apps/librelingo_json_export; poetry install
```
